random_seed: 1984

feature_names:
  - intensity # size: 1
#  - return_number # size: 5 (one-hot)
  #  - number_of_returns # size: 5 (one-hot)
  - colors # size: 3
num_features: 4


num_classes: 10      #Si 2 classes, indiquer 1. Sinon, indiquer normalement le nb de classes.



input_mapping:
 0: 0
 1: 1
 2: 1
 3: 1
 4: 2
 5: 3
 6: 4
 7: 5
 8: 5
 9: 5
 10: 6
 11: 7
 12: 8
 13: 8
 14: 0
 15: 9




voxel_size: 0.003


batch_size: 4
test_batch_size: 1
epochs: 200
loss: FocalLoss                      #Either FocalTverskyLoss or FocalLoss

loss_weights: [1/(0.0167+0.0009),1/(0.2778+0.3081+0.0581+0.0115+0.0099),1/0.1393,1/(0.0453+0.0373+0.0250),1/0.0042,1/0.0016,1/(0.0371+0.0131),1/0.0134]             #Either [alpha, beta] for FocalTverskyLoss or [w1, w2, ..., wi] for FocalLoss with i classes

patience: 50
weights_name: ''             #Name of the weight file that will be saved in /model_weights


train_transforms:
  - name: Intensity_RGB_Variation
    params:
      feature_names: ${feature_names}
  - name: Scale
    params:
      feature_names: ${feature_names}
  #  - name: Noise
  #    params:
  #      feature_names: ${feature_names}
  - name: Rotate
    params:
      feature_names: ${feature_names}
  - name: RandomDelete
    params:
      feature_names: ${feature_names}
  - name: RandomCrop
    params:
      feature_names: ${feature_names}
  - name: NormalizeCoordinates
    #  - name: Flip
    #    params:
    #      feature_names: ${feature_names}
  - name: NormalizeFeatures
    params:
      feature_names: ${feature_names}
  - name: RemapClassification
    params:
      class_mapping: ${input_mapping}


test_transforms:
  - name: NormalizeCoordinates
  - name: NormalizeFeatures
    params:
      feature_names: ${feature_names}
  - name: RemapClassification
    params:
      class_mapping: ${input_mapping}