random_seed: 1984

feature_names:
  - intensity # size: 1
#  - return_number # size: 5 (one-hot)
  #  - number_of_returns # size: 5 (one-hot)
  - colors # size: 3
num_features: 4


num_classes: 3      #Si 2 classes, indiquer 1. Sinon, indiquer normalement le nb de classes.



input_mapping:
 0: 0
 1: 0
 2: 0
 3: 0
 4: 1
 5: 2
 6: 0
 7: 0
 8: 0
 9: 0
 10: 0
 11: 0
 12: 0
 13: 0
 14: 0
 15: 0




voxel_size: 0.002


batch_size: 4
test_batch_size: 1
epochs: 200
loss: FocalLoss                      #Either FocalTverskyLoss or FocalLoss

loss_weights: [11,1,3,1.5]

patience: 50
weights_name: ''             #Name of the weight file that will be saved in /model_weights


train_transforms:
  - name: Intensity_RGB_Variation
    params:
      feature_names: ${feature_names}
  - name: Scale
    params:
      feature_names: ${feature_names}
  #  - name: Noise
  #    params:
  #      feature_names: ${feature_names}
  - name: Rotate
    params:
      feature_names: ${feature_names}
  - name: RandomDelete
    params:
      feature_names: ${feature_names}
  - name: RandomCrop
    params:
      feature_names: ${feature_names}
  - name: NormalizeCoordinates
    #  - name: Flip
    #    params:
    #      feature_names: ${feature_names}
  - name: NormalizeFeatures
    params:
      feature_names: ${feature_names}
  - name: RemapClassification
    params:
      class_mapping: ${input_mapping}


test_transforms:
  - name: NormalizeCoordinates
  - name: NormalizeFeatures
    params:
      feature_names: ${feature_names}
  - name: RemapClassification
    params:
      class_mapping: ${input_mapping}