random_seed: 1984


feature_names:
#  - intensity # size: 1
#  - return_number # size: 5 (one-hot)
  #  - number_of_returns # size: 5 (one-hot)
  - colors # size: 3
num_features: 3

num_classes: 6    #Si 2 classes, indiquer 1. Sinon, indiquer normalement le nb de classes.

input_mapping:
 0: 0 #unclass
 1: 1 #ground
 2: 2 #pole
 3: 2 #pano
 4: 2 #potelet
 5: 3 #Tronc
 6: 4 #Vegetation
 7: 5 #batiment
 8: 5 #ancien murs, j'ai oublier de changer certains points.
 9: 5 #murs
 10: 5 #fences
 11: 0
 12: 0


voxel_size: 0.08

batch_size: 2
test_batch_size: 1
epochs: 2000
loss: FocalTverskyLoss_multiclass                      #Either FocalTverskyLoss or FocalLoss

loss_weights: [[0.4,0.4,1,1,0.9,0.7],[1,0.4,1,1,0.6,0.7]]

patience: 500
weights_name: ''


train_transforms:
  - name: Rotate
    params:
      feature_names: ${feature_names}
  - name: Flip
    params:
      feature_names: ${feature_names}
  - name: Scale
    params:
      feature_names: ${feature_names}
  - name: RandomDelete
    params:
      feature_names: ${feature_names}
#  - name: RandomCrop
#    params:
#      feature_names: ${feature_names}
#  - name: AddRandomPoints
  - name: ElasticDistortion
  - name: ShearTransform
  - name: StretchTransform
  - name: Intensity_RGB_Variation
    params:
      feature_names: ${feature_names}
  - name: Noise
    params:
      feature_names: ${feature_names}
  - name: NormalizeCoordinates
  - name: NormalizeFeatures
    params:
      feature_names: ${feature_names}
  - name: RemapClassification
    params:
      class_mapping: ${input_mapping}

val_transforms:
  - name: NormalizeCoordinates
  - name: NormalizeFeatures
    params:
      feature_names: ${feature_names}
  - name: RemapClassification
    params:
      class_mapping: ${input_mapping}


test_transforms:
  - name: NormalizeCoordinates_predict
  - name: NormalizeFeatures
    params:
      feature_names: ${feature_names}
  - name: RemapClassification
    params:
      class_mapping: ${input_mapping}